version: "2"

volumes:
  nfsjenkins:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.100,rw
      device: ":/mnt/barracuda/nfsjenkins"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - nfsjenkins:/var/jenkins_home